package com.deezyWallet.transaction.dto.response;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import com.deezyWallet.transaction.enums.TransactionStatusEnum;
import com.deezyWallet.transaction.enums.TransactionTypeEnum;
import com.fasterxml.jackson.annotation.JsonInclude;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Transaction response DTO — returned to clients after creating or querying a txn.
 *
 * WHY no fraudScore in the response?
 *   Returning the fraud score to the client leaks information about our fraud
 *   model — an attacker could probe with small variations to learn the model's
 *   thresholds. Fraud score is an internal field visible only in admin UI.
 *
 * WHY no failureReason for user-facing endpoints?
 *   "WALLET_DEBIT_FAILED: blockedBalance > availableBalance" is internal detail.
 *   Users see a human-readable message from the UI layer based on the status.
 *   failureReason is included for admin responses via a separate AdminTransactionResponse.
 *
 * statusDescription:
 *   A human-readable explanation of the current status.
 *   Generated by the mapper — not stored in DB.
 *   Gives clients a label for their transaction history UI without requiring
 *   them to maintain a status → display string mapping.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class TransactionResponse {

	private String            transactionId;
	private TransactionTypeEnum   type;
	private TransactionStatusEnum status;
	private String            statusDescription;  // human-readable, e.g. "Payment successful"

	private BigDecimal        amount;
	private String            currency;
	private String            description;

	private String            senderUserId;
	private String            receiverUserId;     // null for top-ups

	private LocalDateTime     createdAt;
	private LocalDateTime     completedAt;        // null if not yet terminal
}
